### ISSUE TITLE
Interface between sTDA and xTB

### ISSUE THREAD

**Issue by ghutchis** [grimme-lab/xtb4stda#1]
With the update to XTB v6, the previous interface to sTDA seemingly broke (i.e., it didn't save the same temporary files).

Is there a new way to run STDA from an XTB calculation? Are you supposed to dump a `molden` file?

**Comment by awvwgk** [comment]
Sorry for moving this issue all around GH. Now, finally we are in the right place here *and* I am able to close it as resolved.

**Comment by wwww0wwww** [comment]
Hi, I noticed that this topic has been closed, yet I still have some problem with it. I used --molden to get the molden.input file using GFN2-xtb and try to use it as input file for sTDA, however I always get the following error message: 
MO norm  1  0.572456701548246     
internal MO norm error
So where is the problem here?

**Comment by mdewergi** [comment]
You should use xtb4stda as a ground state calculation instead of GFN2-xTB because it was designed for this purpose.
Nevertheless, they are different ways to define things in molden files. This is why in stda, you can choose the type of molden file with -sty 1 to 3. If you read the doc, there is also a command to check the number you need to use.

**Comment by wwww0wwww** [comment]
Thank you! The problem is solved with -sty 0. But I wonder if there is any problem using GFN2-xTB (or GFNn-xTB) for ground state calculation?

**Comment by mdewergi** [comment]
This has never been tested but they are not specially designed for molecular response properties or excited state calculations. Meaning that in xtb4stda, the basis set and the Hamiltonian were specially designed for such properties in order to give good accuracy. Note also that when using xtb4stda, it will enable in stda a special option for this purpose called kshift that improves also the results. You should have a look to the sTDA-xTB paper and the manual for more informations.
